modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="MIT"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="retromod" #mandatory
version="1.0" #mandatory
 # A display name for the mod
displayName="Retro Mod" #mandatory
logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
credits="Me" #optional
# A text field displayed in the mod UI
authors="wildmonke" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
chuj
'''

